//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedEmployeeDeduction
    {
        public int AssignedEmployeeDeductionID { get; set; }
        public int DeductionId { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public int UserPersonalInformationID { get; set; }
    }
}
