//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicPay
    {
        public int BasicPayId { get; set; }
        public Nullable<decimal> BasicPayValue { get; set; }
        public string BasicPayDescription { get; set; }
        public int UserPersonalInformationId { get; set; }
    }
}
