//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollTransaction
    {
        public int PayrollTransactionId { get; set; }
        public int PayrollPeriodId { get; set; }
        public int UserPersonalInformationId { get; set; }
        public Nullable<int> IncomeId { get; set; }
        public Nullable<decimal> CustomIncomeAmount { get; set; }
        public Nullable<int> DeductionId { get; set; }
        public Nullable<decimal> CustomDeductionAmount { get; set; }
        public Nullable<decimal> TotalDeductionAmount { get; set; }
        public Nullable<decimal> TotalIncomeAmount { get; set; }
    }
}
