//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollTransactionIncome
    {
        public int PayrollTransactionIncomeId { get; set; }
        public Nullable<int> UserPersonalInformationid { get; set; }
        public Nullable<int> PayrollPeriodId { get; set; }
        public Nullable<int> IncomeId { get; set; }
        public Nullable<decimal> CustomIncomeAmount { get; set; }
    }
}
