//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollPeriod
    {
        public int PayrollPeriodId { get; set; }
        public string PayrollPeriodDescription { get; set; }
        public Nullable<int> Year { get; set; }
        public string Month { get; set; }
        public System.DateTime PayPeriodFrom { get; set; }
        public System.DateTime PayPeriodTo { get; set; }
        public Nullable<int> WorkDays { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
    }
}
